name: "Setup AWS credentials"
description: "Setup AWS credentials"
inputs:
  aws-environment: # id of input
    description: "AWS environment DEVE / UAT / PROD"
    required: true
    default: "DEVE"
outputs:
  time:
    description: "The time we greeted you"
runs:
  using: "node12"
  main: "index.js"
