name: "Test"
on:
  workflow_dispatch:
    inputs:
      AWS_ENVIRONMENT:
        description: AWS environment DEVE / UAT / PROD
        required: true
        default: DEVE

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup AWS credentials
        id: SetupAWS
        uses: Srovnejto/sandbox-gh_actions/setup-aws-credentials@v8
        with:
          AWS_REGION: eu-central-1
          AWS_ENVIRONMENT: ${{ github.event.inputs.AWS_ENVIRONMENT }}
          DEVE_AWS_ACCESS_KEY_ID: ${{ secrets.DEVE_AWS_ACCESS_KEY_ID }}
          DEVE_AWS_SECRET_ACCESS_KEY: ${{ secrets.DEVE_AWS_SECRET_ACCESS_KEY }}
          UAT_AWS_ACCESS_KEY_ID: ${{ secrets.UAT_AWS_ACCESS_KEY_ID }}
          UAT_AWS_SECRET_ACCESS_KEY: ${{ secrets.UAT_AWS_SECRET_ACCESS_KEY }}
          PROD_AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          PROD_AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}

      - name: Test environment variable
        run: echo "AWS_ACCESS_KEY_ID ${{ env.AWS_ACCESS_KEY_ID }}"

      - name: Get cloudformation stack outputs
        shell: pwsh
        run: |
          aws cloudformation describe-stacks --stack-name leadgen-storage-DEV  > StackDescription.json
          $outputs = (Get-Content StackDescription.json | ConvertFrom-Json).Stacks[0].Outputs
          echo $outputs
      #- name: Run Node.js
      #  run: |
      #    npm install
      #    npm run compile
      #    node built/app.js
