name: "Test"
on:
  workflow_dispatch:
    inputs:
      AWS_ENVIRONMENT:
        description: AWS environment DEV / UAT / PROD
        required: true
        default: DEV
      STACK_NAME:
        description: Stack name
        required: true
        default: leadgen-storage-DEV
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Log into GitHub Container Registry
        run: |
          echo "${{ secrets.BENDER_TOKEN  }}" | docker login https://ghcr.io --username srt-bender --password-stdin
          echo cat ~/.docker/config.json
