name: "Test"
on:
  workflow_dispatch:
    inputs:
      AWS_ENVIRONMENT:
        description: AWS environment DEV / UAT / PROD
        required: true
        default: DEV

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup AWS credentials
        uses: Srovnejto/sandbox-gh_actions/setup-aws-credentials@v12
        with:
          AWS_REGION: eu-central-1
          AWS_ENVIRONMENT: ${{ github.event.inputs.AWS_ENVIRONMENT }}
          DEV_AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          DEV_AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          UAT_AWS_ACCESS_KEY_ID: ${{ secrets.UAT_AWS_ACCESS_KEY_ID }}
          UAT_AWS_SECRET_ACCESS_KEY: ${{ secrets.UAT_AWS_SECRET_ACCESS_KEY }}
          PROD_AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          PROD_AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}

      - name: Deploy SAM template
        uses: Srovnejto/sandbox-gh_actions/deploy-sam-template@v12
        with:
          STACK_NAME: eu-central-1
          PARAMETER_OVERRIDES: ""
          TAGS: ""

      - name: Get cloudformation stack outputs
        shell: pwsh
        run: |
          aws cloudformation describe-stacks --stack-name leadgen-storage-DEV  > StackDescription.json
          $outputs = (Get-Content StackDescription.json | ConvertFrom-Json).Stacks[0].Outputs
