name: "Test"
on:
  workflow_dispatch:
    inputs:
      JsonInput:
        description: "JSON input"
        required: true
        default: '{"VUE_APP_API_URL":"https://customer.srovnejto.cz/api","VUE_APP_FB_APP_ID":"619410902046565","VUE_APP_GOOGLE_CLIENT_ID":"524072367074-99rdeit5beofisknltkisa9ju4t6r1pt.apps.googleusercontent.com"}'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      DEVE_AWS_ACCESS_KEY_ID: ${{ secrets.DEVE_AWS_ACCESS_KEY_ID }}
      DEVE_AWS_SECRET_ACCESS_KEY: ${{ secrets.DEVE_AWS_SECRET_ACCESS_KEY }}
      UAT_AWS_ACCESS_KEY_ID: ${{ secrets.UAT_AWS_ACCESS_KEY_ID }}
      UAT_AWS_SECRET_ACCESS_KEY: ${{ secrets.UAT_AWS_SECRET_ACCESS_KEY }}
      PROD_AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      PROD_AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Node.js
        run: |
          npm install
          npm run compile
          node built/app.js
